# Generated by Django 5.2.12 on 2026-04-06 12:24

import django.db.models.deletion
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


def _seed_alimentos_base(apps, schema_editor):
    AlimentoNutricional = apps.get_model('plataforma', 'AlimentoNutricional')
    # Valores aproximados por 100 g (referência TACO / tabelas usuais).
    seeds = [
        ('Arroz branco cozido', 130, 28.0, 2.5, 0.2, 0.3, 1, 4, 0.3),
        ('Feijão preto cozido', 77, 14.0, 5.1, 0.5, 4.5, 2, 20, 1.5),
        ('Frango peito grelhado', 159, 0, 32.1, 3.2, 0, 56, 8, 0.4),
        ('Ovo de galinha cozido', 146, 0.6, 13.3, 9.5, 0, 124, 38, 1.2),
        ('Banana prata', 98, 26.0, 1.3, 0.3, 2.0, 1, 5, 0.3),
        ('Maçã com casca', 63, 16.6, 0.2, 0.2, 2.0, 1, 7, 0.1),
        ('Aveia em flocos', 394, 66.6, 13.9, 6.9, 9.1, 5, 45, 4.5),
        ('Leite desnatado', 35, 5.0, 3.4, 0.1, 0, 43, 120, 0.1),
        ('Pão francês', 300, 59.6, 8.0, 3.1, 2.3, 648, 91, 1.2),
        ('Azeite de oliva extravirgem', 884, 0, 0, 100, 0, 2, 1, 0.4),
        ('Batata inglesa cozida', 52, 11.9, 1.2, 0.1, 1.8, 4, 5, 0.3),
        ('Brócolos cozidos', 35, 7.2, 2.4, 0.4, 3.3, 33, 47, 0.7),
        ('Tomate cru', 15, 3.1, 1.1, 0.1, 1.2, 5, 10, 0.2),
        ('Iogurte natural desnatado', 41, 5.8, 3.8, 0.1, 0, 46, 120, 0.1),
        ('Queijo minas frescal', 264, 3.2, 17.4, 20.2, 0, 580, 579, 0.2),
        ('Cenoura cozida', 35, 8.0, 0.8, 0.2, 2.6, 55, 30, 0.2),
        ('Tapioca (goma hidratada cozida)', 88, 22.0, 0.1, 0.1, 0.2, 2, 6, 0.5),
        ('Mandioca cozida', 125, 30.1, 0.6, 0.3, 1.6, 1, 35, 0.3),
        ('Atum em conserva (água)', 116, 0, 25.5, 0.9, 0, 320, 8, 1.2),
    ]
    for row in seeds:
        nome = row[0]
        if AlimentoNutricional.objects.filter(nutri_id__isnull=True, nome=nome).exists():
            continue
        AlimentoNutricional.objects.create(
            nutri_id=None,
            nome=nome,
            eh_prato=False,
            kcal_100g=Decimal(str(row[1])),
            carboidratos_g_100g=Decimal(str(row[2])),
            proteinas_g_100g=Decimal(str(row[3])),
            gorduras_g_100g=Decimal(str(row[4])),
            fibra_g_100g=Decimal(str(row[5])),
            sodio_mg_100g=Decimal(str(row[6])),
            calcio_mg_100g=Decimal(str(row[7])),
            ferro_mg_100g=Decimal(str(row[8])),
        )


def _unseed_alimentos_base(apps, schema_editor):
    AlimentoNutricional = apps.get_model('plataforma', 'AlimentoNutricional')
    AlimentoNutricional.objects.filter(nutri_id__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_paciente_situacao_meta_anotacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacaopaciente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AlimentoNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('eh_prato', models.BooleanField(default=False, help_text='Marque se for um prato com valores já agregados por 100 g.', verbose_name='Prato / receita composta')),
                ('kcal_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Energia (kcal/100g)')),
                ('carboidratos_g_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Carboidratos (g/100g)')),
                ('proteinas_g_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Proteínas (g/100g)')),
                ('gorduras_g_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Gorduras (g/100g)')),
                ('fibra_g_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Fibra (g/100g)')),
                ('sodio_mg_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Sódio (mg/100g)')),
                ('calcio_mg_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cálcio (mg/100g)')),
                ('ferro_mg_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ferro (mg/100g)')),
                ('nutri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alimentos_custom', to=settings.AUTH_USER_MODEL, verbose_name='Nutricionista (vazio = base)')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemRefeicaoAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_gramas', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantidade (g)')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_em_refeicoes', to='plataforma.alimentonutricional')),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_alimentos', to='plataforma.refeicao')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(_seed_alimentos_base, _unseed_alimentos_base),
    ]
