# Generated by Django 5.2.12 on 2026-04-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_alimentos_nutricionais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcao',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='opcao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='opcao', verbose_name='Imagem (opcional)'),
        ),
    ]
