# Generated by Django 5.2.12 on 2026-04-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_opcao_imagem_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcao',
            name='titulo',
            field=models.CharField(blank=True, help_text='Opcional. Aparece em destaque no cartão (ex.: «Sugestão de lanche»).', max_length=120, verbose_name='Título curto'),
        ),
    ]
