# Generated by Django 4.2.29 on 2026-04-15 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plataforma', '0010_opcao_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoAntropometrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, help_text='Motivo da consulta, observações gerais e objetivos.', verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data da avaliação')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (cm)')),
                ('peso_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso atual (kg)')),
                ('peso_ideal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso ideal (kg)')),
                ('braco_dir_contraido', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Braço direito contraído (cm)')),
                ('braco_esq_contraido', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Braço esquerdo contraído (cm)')),
                ('braco_dir_relaxado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Braço direito relaxado (cm)')),
                ('braco_esq_relaxado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Braço esquerdo relaxado (cm)')),
                ('antebraco_dir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Antebraço direito (cm)')),
                ('antebraco_esq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Antebraço esquerdo (cm)')),
                ('punho_dir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Punho direito (cm)')),
                ('punho_esq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Punho esquerdo (cm)')),
                ('tronco', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tronco (cm)')),
                ('ombro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ombro (cm)')),
                ('peitoral', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peitoral (cm)')),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cintura (cm)')),
                ('abdomen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Abdómen (cm)')),
                ('quadril', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Quadril (cm)')),
                ('coxa_dir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Coxa direita (cm)')),
                ('coxa_esq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Coxa esquerda (cm)')),
                ('panturrilha_dir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Panturrilha direita (cm)')),
                ('panturrilha_esq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Panturrilha esquerda (cm)')),
                ('dobras_cutaneas', models.TextField(blank=True, help_text='Registo das dobras (mm) e fórmula utilizada, se aplicável.', verbose_name='Dobras / pregas cutâneas')),
                ('bioimpedancia', models.TextField(blank=True, help_text='Valores do equipamento, percentagens, água, etc.', verbose_name='Bioimpedância')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nutri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_antropometricas', to='plataforma.pacientes')),
            ],
            options={
                'verbose_name': 'Avaliação antropométrica',
                'verbose_name_plural': 'Avaliações antropométricas',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GastoEnergetico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / contexto')),
                ('data', models.DateField(verbose_name='Data')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (cm)')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('calculos_protocolos', models.TextField(blank=True, help_text='Ex.: Harris-Benedict, Mifflin, TEE, etc.', verbose_name='Cálculos por protocolos')),
                ('nivel_atividade_met', models.TextField(blank=True, help_text='Classificação ou tabela MET utilizada.', verbose_name='Nível de atividade (MET)')),
                ('atividades_fisicas', models.TextField(blank=True, help_text='Tipo, duração, frequência e MET estimados.', verbose_name='Atividades físicas')),
                ('fator_lesao', models.DecimalField(blank=True, decimal_places=3, help_text='Fator multiplicativo em situação de lesão, cirurgia ou inflamação.', max_digits=6, null=True, verbose_name='Fator de lesão / estresse')),
                ('massa_magra_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Massa magra (kg)')),
                ('resultados', models.TextField(blank=True, help_text='GET, gasto estimado, recomendações energéticas.', verbose_name='Resultados')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nutri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_energeticos', to='plataforma.pacientes')),
            ],
            options={
                'verbose_name': 'Gasto energético',
                'verbose_name_plural': 'Gastos energéticos',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FotoAvaliacaoAntropometrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='avaliacoes/fotos', verbose_name='Foto')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='plataforma.avaliacaoantropometrica')),
            ],
            options={
                'verbose_name': 'Foto da avaliação',
                'verbose_name_plural': 'Fotos da avaliação',
            },
        ),
        migrations.CreateModel(
            name='FichaAnamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(help_text='Queixa principal, história, hábitos, patologias, medicações, etc.', max_length=20000, verbose_name='Conteúdo da ficha')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nutri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_anamnese', to='plataforma.pacientes')),
            ],
            options={
                'verbose_name': 'Ficha de anamnese',
                'verbose_name_plural': 'Fichas de anamnese',
                'ordering': ['-atualizado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AnexoExameAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='avaliacoes/exames', verbose_name='Anexo (exame)')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_exames', to='plataforma.avaliacaoantropometrica')),
            ],
            options={
                'verbose_name': 'Anexo de exame',
                'verbose_name_plural': 'Anexos de exames',
            },
        ),
    ]
